compare and update against tfenv
Combed through libexec code to compare against current master of tfenv repo to capture relevant updates.
Incorporated similar changes to bin and test code, but may not have captured everything in test code.

diff --git a/libexec/tgenv-install b/libexec/tgenv-install
--- a/libexec/tgenv-install
+++ b/libexec/tgenv-install
@@ -1,19 +1,7 @@
 #!/usr/bin/env bash
 
-function error_and_die() {
-  echo -e "tgenv: $(basename ${0}): \033[0;31m[ERROR] ${1}\033[0;39m" >&2
-  exit 1
-}
-
-function warn_and_continue() {
-  echo -e "tgenv: $(basename ${0}): \033[0;33m[WARN] ${1}\033[0;39m" >&2
-}
-
-function info() {
-  echo -e "\033[0;32m[INFO] ${1}\033[0;39m"
-}
-
 [ -n "${TGENV_DEBUG}" ] && set -x
+source ${TGENV_ROOT}/libexec/helpers
 
 [ "${#}" -gt 1 ] && error_and_die "usage: tgenv install [<version>]"
 
@@ -33,10 +21,10 @@ if [[ "${version_requested}" =~ ^latest\:.*$ ]]; then
   regex="${version_requested##*\:}"
 elif [[ "${version_requested}" =~ ^latest$ ]]; then
   version="${version_requested}"
-  regex=""
+  regex="^[0-9]\+\.[0-9]\+\.[0-9]\+$"
 else
   version="${version_requested}"
-  regex="${version_requested}"
+  regex="^${version_requested}$"
 fi
 
 [ -n "${version}" ] || error_and_die "Version is not specified"
@@ -49,15 +37,16 @@ if [ -f "${dst_path}/terragrunt" ]; then
   exit 0
 fi
 
+TGENV_ARCH=${TGENV_ARCH:-amd64}
 case "$(uname -s)" in
   Darwin*)
-    os="darwin_amd64"
+    os="darwin_${TGENV_ARCH}"
     ;;
   MINGW64*)
-    os="windows_amd64"
+    os="windows_${TGENV_ARCH}"
     ;;
   *)
-    os="linux_amd64"
+    os="linux_${TGENV_ARCH}"
     ;;
 esac
 
@@ -68,10 +57,12 @@ tarball_name="terragrunt_${os}"
 info "Installing Terragrunt v${version}"
 
 mkdir -p "${dst_path}" || error_and_die "Failed to make directory ${dst_path}"
+trap "rm -rf ${dst_path}" EXIT;
 
 info "Downloading release tarball from ${version_url}/${tarball_name}"
-curl -# --tlsv1.2 --location-trusted -f -o "${dst_path}/terragrunt" "${version_url}/${tarball_name}" || error_and_die "Tarball download failed"
+curlw -# -f -o "${dst_path}/terragrunt" "${version_url}/${tarball_name}" || error_and_die "Tarball download failed"
 
 chmod +x "${dst_path}/terragrunt" || error_and_die "Change rights failed"
 
 info "Installation of terragrunt v${version} successful"
+tgenv-use "$version"
diff --git a/libexec/tgenv-use b/libexec/tgenv-use
--- a/libexec/tgenv-use
+++ b/libexec/tgenv-use
@@ -1,11 +1,7 @@
 #!/usr/bin/env bash
 
-function error_and_die() {
-  echo -e "tgenv: ${0}: ${1}" >&2
-  exit 1
-}
-
 [ -n "${TGENV_DEBUG}" ] && set -x
+source ${TGENV_ROOT}/libexec/helpers
 
 [ ${#} -ne 1 ] && error_and_die "usage: tgenv use <version>"
 
@@ -21,7 +17,7 @@ elif [[ "${version_requested}" =~ ^latest$ ]]; then
   regex=""
 else
   version="${version_requested}"
-  regex="${version_requested}"
+  regex="^${version_requested}$"
 fi
 
 [ -d "${TGENV_ROOT}/versions" ] \
@@ -41,5 +37,7 @@ target_path=${TGENV_ROOT}/versions/${version}
 [ -x ${target_path}/terragrunt ] \
   || error_and_die "Version directory for ${version} is present, but the terragrunt binary is not executable! Manual intervention required. "
 
-echo "${version}" > "${TGENV_ROOT}/version"
-terragrunt --version || error_and_die "'terragrunt --version' failed. Something is seriously wrong"
+info "Switching to v${version}"
+echo "${version}" > "$(tgenv-version-file)" || error_and_die "'switch to v${version} failed'"
+terragrunt --version 1>/dev/null || error_and_die "'terragrunt --version' failed. Something is seriously wrong"
+info "Switching completed"
